name: Check pull request age
env:
  GITHUB_TOKEN: ${{ secrets.CHECK_PRS_GITHUB_TOKEN }}
  REPOSITORY_OWNER: dxw
  REPOSITORY_NAME: tech-team-rfcs

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 * * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run check:prs
